/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED
#define CONFIG_MIPS 1
#define CONFIG_UCLINUX 1
#define CONFIG_UID16 1

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1

/*
 * Machine selection
 */
#define CONFIG_PLAYSTATION 1
#undef  CONFIG_MCA
#undef  CONFIG_SBUS
#undef  CONFIG_ISA
#undef  CONFIG_EISA
#undef  CONFIG_PCI
#undef  CONFIG_I8259

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#undef  CONFIG_MODVERSIONS
#define CONFIG_KMOD 1

/*
 * CPU selection
 */
#define CONFIG_CPU_R3000 1
#undef  CONFIG_CPU_R6000
#undef  CONFIG_CPU_R4300
#undef  CONFIG_CPU_R4X00
#undef  CONFIG_CPU_R5000
#undef  CONFIG_CPU_R5432
#undef  CONFIG_CPU_RM7000
#undef  CONFIG_CPU_NEVADA
#undef  CONFIG_CPU_R8000
#undef  CONFIG_CPU_R10000
#undef  CONFIG_CPU_MIPS32
#undef  CONFIG_CPU_ADVANCED

/*
 * General setup
 */
#define CONFIG_CPU_LITTLE_ENDIAN 1
#define CONFIG_MIPS_FPU_EMULATOR 1
#define CONFIG_KCORE_ELF 1
#define CONFIG_ELF_KERNEL 1
#undef  CONFIG_BINFMT_FLAT
#undef  CONFIG_BINFMT_AOUT
#define CONFIG_BINFMT_ELF 1
#undef  CONFIG_BINFMT_MISC
#define CONFIG_NET 1
#define CONFIG_SYSVIPC 1
#undef  CONFIG_BSD_PROCESS_ACCT
#define CONFIG_SYSCTL 1

/*
 * Parallel port support
 */
#undef  CONFIG_PARPORT
#undef  CONFIG_PCMCIA

/*
 * Memory Technology Devices (MTD)
 */
#undef  CONFIG_MTD

/*
 * Block devices
 */
#undef  CONFIG_BLK_DEV_FD
#undef  CONFIG_BLK_DEV_XD
#undef  CONFIG_PARIDE
#undef  CONFIG_BLK_CPQ_DA
#undef  CONFIG_BLK_CPQ_CISS_DA
#undef  CONFIG_BLK_DEV_DAC960
#undef  CONFIG_BLK_DEV_LOOP
#undef  CONFIG_BLK_DEV_NBD
#undef  CONFIG_BLK_DEV_RAM
#define CONFIG_BLK_DEV_RAM_MODULE 1
#define CONFIG_BLK_DEV_RAM_SIZE (4096)
#undef  CONFIG_BLK_DEV_INITRD
#undef  CONFIG_BLK_DEV_BLKMEM
#undef  CONFIG_PSX_MEM_CARD
#define CONFIG_PSX_MEM_CARD_MODULE 1

/*
 * Multi-device support (RAID and LVM)
 */
#define CONFIG_MD 1
#undef  CONFIG_BLK_DEV_MD
#define CONFIG_BLK_DEV_MD_MODULE 1
#undef  CONFIG_MD_LINEAR
#define CONFIG_MD_LINEAR_MODULE 1
#undef  CONFIG_MD_RAID0
#undef  CONFIG_MD_RAID1
#undef  CONFIG_MD_RAID5
#undef  CONFIG_BLK_DEV_LVM
#undef  CONFIG_LVM_PROC_FS

/*
 * Networking options
 */
#define CONFIG_PACKET 1
#undef  CONFIG_PACKET_MMAP
#undef  CONFIG_NETLINK
#undef  CONFIG_NETFILTER
#undef  CONFIG_FILTER
#define CONFIG_UNIX 1
#undef  CONFIG_INET
#undef  CONFIG_ATM
#undef  CONFIG_IPX
#undef  CONFIG_ATALK
#undef  CONFIG_DECNET
#undef  CONFIG_BRIDGE
#undef  CONFIG_X25
#undef  CONFIG_LAPB
#undef  CONFIG_LLC
#undef  CONFIG_NET_DIVERT
#undef  CONFIG_WAN_ROUTER
#undef  CONFIG_NET_FASTROUTE
#undef  CONFIG_NET_HW_FLOWCONTROL

/*
 * QoS and/or fair queueing
 */
#undef  CONFIG_NET_SCHED

/*
 * ATA/IDE/MFM/RLL support
 */
#undef  CONFIG_IDE
#undef  CONFIG_BLK_DEV_IDE_MODES
#undef  CONFIG_BLK_DEV_HD

/*
 * Network device support
 */
#define CONFIG_NETDEVICES 1
#undef  CONFIG_DUMMY
#undef  CONFIG_SLIP
#undef  CONFIG_PPP

/*
 * PlayStation Character devices
 */
#define CONFIG_PS_SIO_CONSOLE 1
#undef  CONFIG_PS_GPU_CONSOLE

/*
 * File systems
 */
#undef  CONFIG_QUOTA
#define CONFIG_AUTOFS_FS 1
#define CONFIG_AUTOFS4_FS 1
#undef  CONFIG_ADFS_FS
#undef  CONFIG_ADFS_FS_RW
#undef  CONFIG_AFFS_FS
#undef  CONFIG_HFS_FS
#undef  CONFIG_BFS_FS
#undef  CONFIG_FAT_FS
#undef  CONFIG_MSDOS_FS
#undef  CONFIG_UMSDOS_FS
#undef  CONFIG_VFAT_FS
#undef  CONFIG_EFS_FS
#undef  CONFIG_JFFS_FS
#undef  CONFIG_CRAMFS
#undef  CONFIG_RAMFS
#define CONFIG_ISO9660_FS 1
#undef  CONFIG_JOLIET
#undef  CONFIG_MINIX_FS
#undef  CONFIG_NTFS_FS
#undef  CONFIG_NTFS_RW
#undef  CONFIG_HPFS_FS
#define CONFIG_PROC_FS 1
#undef  CONFIG_DEVFS_FS
#undef  CONFIG_DEVFS_MOUNT
#undef  CONFIG_DEVFS_DEBUG
#undef  CONFIG_DEVPTS_FS
#undef  CONFIG_QNX4FS_FS
#undef  CONFIG_QNX4FS_RW
#undef  CONFIG_ROMFS_FS
#define CONFIG_EXT2_FS 1
#undef  CONFIG_SYSV_FS
#undef  CONFIG_SYSV_FS_WRITE
#undef  CONFIG_UDF_FS
#undef  CONFIG_UDF_RW
#undef  CONFIG_UFS_FS
#undef  CONFIG_UFS_FS_WRITE

/*
 * Network File Systems
 */
#undef  CONFIG_CODA_FS
#undef  CONFIG_NFS_FS
#undef  CONFIG_NFS_V3
#undef  CONFIG_ROOT_NFS
#undef  CONFIG_NFSD
#undef  CONFIG_NFSD_V3
#undef  CONFIG_SUNRPC
#undef  CONFIG_LOCKD
#undef  CONFIG_SMB_FS
#undef  CONFIG_NCPFS_NLS

/*
 * Partition Types
 */
#define CONFIG_PARTITION_ADVANCED 1
#undef  CONFIG_ACORN_PARTITION
#undef  CONFIG_OSF_PARTITION
#undef  CONFIG_AMIGA_PARTITION
#undef  CONFIG_ATARI_PARTITION
#undef  CONFIG_MAC_PARTITION
#define CONFIG_MSDOS_PARTITION 1
#undef  CONFIG_BSD_DISKLABEL
#undef  CONFIG_SOLARIS_X86_PARTITION
#undef  CONFIG_UNIXWARE_DISKLABEL
#define CONFIG_SGI_PARTITION 1
#undef  CONFIG_ULTRIX_PARTITION
#undef  CONFIG_SUN_PARTITION
#undef  CONFIG_SMB_NLS
#undef  CONFIG_NLS

/*
 * Console drivers
 */
#undef  CONFIG_GPUPSX_CONSOLE
#undef  CONFIG_PC_KEYB
#define CONFIG_VT 1
#define CONFIG_VT_CONSOLE 1
#define VT_SINGLE_DRIVER 1

/*
 * Sound
 */
#undef  CONFIG_SOUND

/*
 * USB support
 */
#undef  CONFIG_USB

/*
 * Input core support
 */
#undef  CONFIG_INPUT

/*
 * Kernel hacking
 */
#define CONFIG_CROSSCOMPILE 1
#undef  CONFIG_MIPS_FPE_MODULE
#undef  CONFIG_MAGIC_SYSRQ
#undef  CONFIG_MIPS_UNCACHED
